declare module "@mui/material" {
    const AppBar: React.Component;
    const Avatar: React.Component;
    const Backdrop: React.Component;
    const Badge: React.Component;
    const BottomNavigation: React.Component;
    const BottomNavigationAction: React.Component;
    const Box: React.Component;
    const Breadcrumbs: React.Component;
    const Button: React.Component;
    const ButtonBase: React.Component;
    const ButtonGroup: React.Component;
    const Card: React.Component;
    const CardActionArea: React.Component;
    const CardActions: React.Component;
    const CardContent: React.Component;
    const CardHeader: React.Component;
    const CardMedia: React.Component;
    const Checkbox: React.Component;
    const Chip: React.Component;
    const CircularProgress: React.Component;
    const ClickAwayListener: React.Component;
    const Collapse: React.Component;
    const Container: React.Component;
    const CssBaseline: React.Component;
    const Dialog: React.Component;
    const DialogActions: React.Component;
    const DialogContent: React.Component;
    const DialogContentText: React.Component;
    const DialogTitle: React.Component;
    const Divider: React.Component;
    const Drawer: React.Component;
    const ExpansionPanel: React.Component;
    const ExpansionPanelActions: React.Component;
    const ExpansionPanelDetails: React.Component;
    const ExpansionPanelSummary: React.Component;
    const Fab: React.Component;
    const Fade: React.Component;
    const FilledInput: React.Component;
    const FormControl: React.Component;
    const FormControlLabel: React.Component;
    const FormGroup: React.Component;
    const FormHelperText: React.Component;
    const FormLabel: React.Component;
    const Grid: React.Component;
    const GridList: React.Component;
    const GridListTile: React.Component;
    const GridListTileBar: React.Component;
    const Grow: React.Component;
    const Hidden: React.Component;
    const Icon: React.Component;
    const IconButton: React.Component;
    const Input: React.Component;
    const InputAdornment: React.Component;
    const InputBase: React.Component;
    const InputLabel: React.Component;
    const LinearProgress: React.Component;
    const Link: React.Component;
    const List: React.Component;
    const ListItem: React.Component;
    const ListItemAvatar: React.Component;
    const ListItemIcon: React.Component;
    const ListItemSecondaryAction: React.Component;
    const ListItemText: React.Component;
    const ListSubheader: React.Component;
    const Menu: React.Component;
    const MenuItem: React.Component;
    const MenuList: React.Component;
    const MobileStepper: React.Component;
    const Modal: React.Component;
    const ModalManager: React.Component;
    const NativeSelect: React.Component;
    const OutlinedInput: React.Component;
    const Paper: React.Component;
    const Popover: React.Component;
    const Popper: React.Component;
    const Portal: React.Component;
    const Radio: React.Component;
    const RadioGroup: React.Component;
    const RootRef: React.Component;
    const Select: React.Component;
    const Slide: React.Component;
    const Slider: React.Component;
    const Snackbar: React.Component;
    const SnackbarContent: React.Component;
    const Step: React.Component;
    const StepButton: React.Component;
    const StepConnector: React.Component;
    const StepContent: React.Component;
    const StepIcon: React.Component;
    const StepLabel: React.Component;
    const Stepper: React.Component;
    const SvgIcon: React.Component;
    const SwipeableDrawer: React.Component;
    const Switch: React.Component;
    const Tab: React.Component;
    const Table: React.Component;
    const TableBody: React.Component;
    const TableCell: React.Component;
    const TableContainer: React.Component;
    const TableFooter: React.Component;
    const TableHead: React.Component;
    const TablePagination: React.Component;
    const TableRow: React.Component;
    const TableSortLabel: React.Component;
    const Tabs: React.Component;
    const TabScrollButton: React.Component;
    const TextField: React.Component;
    const TextareaAutosize: React.Component;
    const Toolbar: React.Component;
    const Tooltip: React.Component;
    const Typography: React.Component;
    const Zoom: React.Component;
    const ServerStyleSheets: React.Component;
    const StylesProvider: React.Component;
    const MuiThemeProvider: React.Component;
    const ThemeProvider: React.Component;
    const Alert: React.Component;
    const AlertTitle: React.Component;
    const Autocomplete: React.Component;
    const createFilterOptions: React.Component;
    const Pagination: React.Component;
    const usePagination: React.Component;
    const PaginationItem: React.Component;
    const Rating: React.Component;
    const Skeleton: React.Component;
    const SpeedDial: React.Component;
    const SpeedDialAction: React.Component;
    const SpeedDialIcon: React.Component;
    const TabContext: React.Component;
    const TabPanel: React.Component;
    const TabList: React.Component;
    const ToggleButton: React.Component;
    const ToggleButtonGroup: React.Component;
    const TreeItem: React.Component;
    const TreeView: React.Component;
    const useAutocomplete: React.Component;
    const useTabContext: React.Component;
    const getPanelId: React.Component;
    const getTabId: React.Component;
    const AvatarGroup: React.Component;
    function hexToRgb(...args: any): any;
    function rgbToHex(...args: any): any;
    function hslToRgb(...args: any): any;
    function decomposeColor(...args: any): any;
    function recomposeColor(...args: any): any;
    function getContrastRatio(...args: any): any;
    function getLuminance(...args: any): any;
    function emphasize(...args: any): any;
    function alpha(...args: any): any;
    function fade(...args: any): any;
    function darken(...args: any): any;
    function lighten(...args: any): any;
    function useEventCallback(...args: any): any;
    function useForkRef(...args: any): any;
    function useIsFocusVisible(...args: any): any;
    function useMediaQuery(...args: any): any;
    function useScrollTrigger(...args: any): any;
}
