/**
 * @fileoverview Typedefs for react generated by generate-typescript-entries in browser runtime
 * @see https://gist.github.com/tripolskypetr/b9c56202cd98935a49389fb46f77ef19
 */
declare module "react" {
  export class Children {
    map: any;
    forEach: any;
    count: any;
    toArray: any;
    only: any;
  }
  export class Component {
    isReactComponent: any;
    setState: any;
    forceUpdate: any;
  }
  export function Fragment(...args: any): any;
  export function Profiler(...args: any): any;
  export class PureComponent {
    isReactComponent: any;
    setState: any;
    forceUpdate: any;
    isPureReactComponent: any;
  }
  export function StrictMode(...args: any): any;
  export function Suspense(...args: any): any;
  export namespace __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED {
    export namespace ReactCurrentDispatcher {
      export class current {
        readContext: any;
        useCallback: any;
        useContext: any;
        useEffect: any;
        useImperativeHandle: any;
        useInsertionEffect: any;
        useLayoutEffect: any;
        useMemo: any;
        useReducer: any;
        useRef: any;
        useState: any;
        useDebugValue: any;
        useDeferredValue: any;
        useTransition: any;
        useMutableSource: any;
        useSyncExternalStore: any;
        useId: any;
        unstable_isNewReconciler: any;
      }
    }
    export class ReactCurrentBatchConfig {
      transition: any;
    }
    export class ReactCurrentOwner {
      current: any;
    }
    export class ReactDebugCurrentFrame {
      setExtraStackFrame: any;
      getCurrentStack: any;
      getStackAddendum: any;
    }
    export class ReactCurrentActQueue {
      current: any;
      isBatchingLegacy: any;
      didScheduleLegacyUpdate: any;
    }
  }
  export function cloneElement(...args: any): any;
  export function createContext(...args: any): any;
  export function createElement(...args: any): any;
  export function createFactory(...args: any): any;
  export function createRef(...args: any): any;
  export function forwardRef(...args: any): any;
  export function isValidElement(...args: any): any;
  export function lazy(...args: any): any;
  export function memo(...args: any): any;
  export function startTransition(...args: any): any;
  export function unstable_act(...args: any): any;
  export function useCallback(...args: any): any;
  export function useContext(...args: any): any;
  export function useDebugValue(...args: any): any;
  export function useDeferredValue(...args: any): any;
  export function useEffect(...args: any): any;
  export function useId(...args: any): any;
  export function useImperativeHandle(...args: any): any;
  export function useInsertionEffect(...args: any): any;
  export function useLayoutEffect(...args: any): any;
  export function useMemo(...args: any): any;
  export function useReducer(...args: any): any;
  export function useRef(...args: any): any;
  export function useState(...args: any): any;
  export function useSyncExternalStore(...args: any): any;
  export function useTransition(...args: any): any;
  export function version(...args: any): any;
}
